name: Weekly Bin Scrape

# Schedule: Runs at 06:00 on Mondays
on:
  schedule:
    - cron: '0 6 * * 1'
  # Allows manual testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          BIN_USERS: ${{ secrets.BIN_USERS }}
        run: python main.py

      - name: Save Calendars
        run: |
          git config --global user.name "BinBot"
          git config --global user.email "binbot@noreply.github.com"
          
          # This adds ALL .ics files created (a.ics, b.ics, etc.)
          git add *.ics
          
          # Only commit if something actually changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update bin calendars" && git push)
